// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipes.Api.Data;

#nullable disable

namespace Recipes.Api.Migrations
{
    [DbContext(typeof(RecipesDbContext))]
    [Migration("20251127175928_SeedUnitsOfMeasurement")]
    partial class SeedUnitsOfMeasurement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Recipes.Api.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitOfMeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("RecipeId", "IngredientId", "UnitOfMeasurementId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitOfMeasurementId");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeTag", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeTags", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeTimeMade", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MadeAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("RecipeId", "MadeAt");

                    b.ToTable("RecipeTimesMade", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.UnitOfMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeasurement", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cec58f72-bbb8-473e-98ac-a8b153c66f77"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4928),
                            Name = "cup",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4934)
                        },
                        new
                        {
                            Id = new Guid("e507aecc-50a0-45d7-b43a-77bb9b3b701c"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4948),
                            Name = "tablespoon",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4949)
                        },
                        new
                        {
                            Id = new Guid("fecd3df0-1165-4c99-9ea3-589867ae8e19"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4951),
                            Name = "teaspoon",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4951)
                        },
                        new
                        {
                            Id = new Guid("537debe5-cdfc-482e-8fb2-6e0956524976"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4952),
                            Name = "ounce",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4953)
                        },
                        new
                        {
                            Id = new Guid("d38a828c-79d9-44f7-a912-d912b97cd1ec"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4954),
                            Name = "pound",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4955)
                        },
                        new
                        {
                            Id = new Guid("00a0409c-8239-4118-9938-8feb598cfe31"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4956),
                            Name = "gram",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4957)
                        },
                        new
                        {
                            Id = new Guid("eeed0d4f-c3df-4665-8712-ba392490dce6"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4958),
                            Name = "kilogram",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4958)
                        },
                        new
                        {
                            Id = new Guid("9a0aa1c9-658b-4769-abd2-7280f6cb9e38"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4960),
                            Name = "milliliter",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4960)
                        },
                        new
                        {
                            Id = new Guid("169ac0d3-a029-471b-a285-87f04f6c80ca"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4962),
                            Name = "liter",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4962)
                        },
                        new
                        {
                            Id = new Guid("4aed97c5-f741-4a2e-bc8c-bccb6e1d5998"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4967),
                            Name = "pinch",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4967)
                        },
                        new
                        {
                            Id = new Guid("efc6654e-9a41-405b-8e2a-14f8e543c3c3"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4969),
                            Name = "dash",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4969)
                        },
                        new
                        {
                            Id = new Guid("e93ac73d-dc29-43ba-b838-2bc23f521e3b"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4970),
                            Name = "whole",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4971)
                        },
                        new
                        {
                            Id = new Guid("eabd7030-1f6d-493f-92b8-1e0b4a25b67f"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4972),
                            Name = "piece",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4973)
                        },
                        new
                        {
                            Id = new Guid("33240855-a90f-4eae-aed9-e5505a760ec7"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4974),
                            Name = "slice",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4975)
                        },
                        new
                        {
                            Id = new Guid("b000f375-1dae-4200-a0bf-d48614dc7b0d"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4976),
                            Name = "clove",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4977)
                        },
                        new
                        {
                            Id = new Guid("dc21eba3-b1f6-4575-8050-739290e6cb4e"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4978),
                            Name = "can",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4978)
                        },
                        new
                        {
                            Id = new Guid("b5bdab3f-077d-442b-9b4e-e4aa0761e7d4"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4980),
                            Name = "package",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4980)
                        },
                        new
                        {
                            Id = new Guid("4fea1e82-8f1d-4b03-95f1-dd167c18c41c"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4984),
                            Name = "jar",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4984)
                        },
                        new
                        {
                            Id = new Guid("1289a211-b2a9-4d05-89f6-b30979271b16"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4986),
                            Name = "bottle",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4986)
                        },
                        new
                        {
                            Id = new Guid("ece62990-f684-4ab9-843f-4d2d076fedf5"),
                            CreatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4987),
                            Name = "box",
                            UpdatedAt = new DateTime(2025, 11, 27, 17, 59, 28, 512, DateTimeKind.Utc).AddTicks(4988)
                        });
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Recipes.Api.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recipes.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipes.Api.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UnitOfMeasurementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeTag", b =>
                {
                    b.HasOne("Recipes.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipes.Api.Models.Tag", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeTimeMade", b =>
                {
                    b.HasOne("Recipes.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeTimesMade")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Recipes.Api.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Recipes.Api.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeTags");

                    b.Navigation("RecipeTimesMade");
                });

            modelBuilder.Entity("Recipes.Api.Models.Tag", b =>
                {
                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("Recipes.Api.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
