// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipes.Api.Data;

#nullable disable

namespace Recipes.Api.Migrations
{
    [DbContext(typeof(RecipesDbContext))]
    [Migration("20251129115230_MakeNotesOptional")]
    partial class MakeNotesOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Recipes.Api.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitOfMeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("RecipeId", "IngredientId", "UnitOfMeasurementId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitOfMeasurementId");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeTag", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeTags", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeTimeMade", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MadeAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("RecipeId", "MadeAt");

                    b.ToTable("RecipeTimesMade", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Recipes.Api.Models.UnitOfMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeasurement", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4265a2d3-67e9-4426-9dff-c1a7d9195e4a"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5781),
                            Name = "cup",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5783)
                        },
                        new
                        {
                            Id = new Guid("adae631d-ef80-4ce9-bef9-abecc53064c3"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5784),
                            Name = "tablespoon",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5785)
                        },
                        new
                        {
                            Id = new Guid("72a62cc4-1232-4838-9f22-b173090017a8"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5786),
                            Name = "teaspoon",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5787)
                        },
                        new
                        {
                            Id = new Guid("ea354b73-fdeb-4ae8-b9ed-5e1fce519076"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5788),
                            Name = "ounce",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5789)
                        },
                        new
                        {
                            Id = new Guid("1eef8b25-ca77-45a9-98fd-72d2334ad6cf"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5790),
                            Name = "pound",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5790)
                        },
                        new
                        {
                            Id = new Guid("6c9c8644-d0dd-4737-886f-c29fdbd8fc91"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5792),
                            Name = "gram",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5792)
                        },
                        new
                        {
                            Id = new Guid("0e14fd54-326a-4fe5-bf77-dff7b0a61041"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5794),
                            Name = "kilogram",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5794)
                        },
                        new
                        {
                            Id = new Guid("f9ef3aa2-6284-43fd-92d9-fbf3c748d622"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5805),
                            Name = "milliliter",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5806)
                        },
                        new
                        {
                            Id = new Guid("8eaa0dac-1a26-4f2f-9518-f389ac1bbb21"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5807),
                            Name = "liter",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5808)
                        },
                        new
                        {
                            Id = new Guid("0294d47c-be81-4f66-9d6e-a897f9e5b2e0"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5809),
                            Name = "pinch",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5810)
                        },
                        new
                        {
                            Id = new Guid("41fa0414-2651-431b-8729-31cbc0482726"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5811),
                            Name = "dash",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5811)
                        },
                        new
                        {
                            Id = new Guid("3fefb99b-5d9f-4505-80c7-ff4ed3b524e3"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5813),
                            Name = "whole",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5813)
                        },
                        new
                        {
                            Id = new Guid("d1f6d478-0940-40c1-98a4-7405a51e95e0"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5815),
                            Name = "piece",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5815)
                        },
                        new
                        {
                            Id = new Guid("18cc0bf8-bbc9-4f42-9daa-6ff1f222028d"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5817),
                            Name = "slice",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5817)
                        },
                        new
                        {
                            Id = new Guid("da9d4ee8-8c2a-4ba7-a250-c5108b15ff98"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5819),
                            Name = "clove",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5819)
                        },
                        new
                        {
                            Id = new Guid("65954c81-7c57-4362-9671-5657f43b6b98"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5823),
                            Name = "can",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5823)
                        },
                        new
                        {
                            Id = new Guid("1bb9e5c4-dec8-47b8-9658-4d0e7ab1619c"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5825),
                            Name = "package",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5825)
                        },
                        new
                        {
                            Id = new Guid("09c9a4d4-35e6-46d2-9bda-c8cf7eab34f2"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5827),
                            Name = "jar",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5827)
                        },
                        new
                        {
                            Id = new Guid("29788a87-6bff-4a90-9b3a-9ff610ec4229"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5828),
                            Name = "bottle",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5829)
                        },
                        new
                        {
                            Id = new Guid("4dc4938c-b1df-404d-82d6-4c90784ab9d1"),
                            CreatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5830),
                            Name = "box",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 52, 29, 801, DateTimeKind.Utc).AddTicks(5831)
                        });
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Recipes.Api.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recipes.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipes.Api.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UnitOfMeasurementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeTag", b =>
                {
                    b.HasOne("Recipes.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipes.Api.Models.Tag", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Recipes.Api.Models.RecipeTimeMade", b =>
                {
                    b.HasOne("Recipes.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeTimesMade")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Recipes.Api.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Recipes.Api.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeTags");

                    b.Navigation("RecipeTimesMade");
                });

            modelBuilder.Entity("Recipes.Api.Models.Tag", b =>
                {
                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("Recipes.Api.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
